-- Studio Spot — seed de lugares reales de Santiago de Chile
-- Dataset curado de cafés de especialidad, espacios de coworking y bibliotecas
-- públicas/universitarias en distintas comunas (Santiago, Providencia, Ñuñoa,
-- Las Condes, Vitacura, La Reina, Estación Central, Macul).
--
-- PROCEDENCIA / HONESTIDAD DEL DATO:
--   * nombre, tipo, comuna, direccion, lat, lng son REALES (verificados por web;
--     las coordenadas son aproximadas pero plausibles según la dirección/comuna).
--   * enchufes, wifi, ruido, ambiente, precio, tiene_banos y congestion NO son
--     medibles públicamente con exactitud: son ESTIMACIONES realistas según el
--     tipo de lugar y lo que se desprende de reseñas. La columna `fuente` indica
--     la procedencia ('web: ...' para el lugar real, '+ estimado' para atributos).
--
-- Idempotencia: usa ON CONFLICT (slug) para poder re-ejecutarse sin duplicar.

insert into places (slug, nombre, tipo, comuna, direccion, lat, lng, descripcion, enchufes, wifi, ruido, ambiente, precio, tiene_banos, horario, congestion, fuente) values
('colmado-coffee-bakery-santiago', 'Colmado Coffee & Bakery', 'cafe', 'Santiago', 'Merced 346, Barrio Lastarria', -33.4371, -70.6406, 'Café de especialidad y panadería escondido en un patio interior del Barrio Lastarria.', 'medio', 'alto', 'animado', 'acogedor, patio interior, panadería artesanal', '$$', true, 'Lun-Dom 08:30-21:00', '{"mañana":"medio","mediodia":"alto","tarde":"medio","noche":"alto"}'::jsonb, 'web: Yelp / La Tercera + estimado por reseñas'),
('cafe-forastero-providencia', 'Café Forastero', 'cafe', 'Providencia', 'Santa Isabel 0165, Barrio Italia', -33.4480, -70.6225, 'Cafetería de especialidad y brunch en Barrio Italia, ideal para trabajar de día.', 'medio', 'alto', 'moderado', 'luminoso, plantas, mesas amplias', '$$', true, 'Lun-Dom 09:00-20:00', '{"mañana":"bajo","mediodia":"alto","tarde":"medio","noche":"bajo"}'::jsonb, 'web: Vivir para Comer + estimado por reseñas'),
('felix-cafe-providencia', 'Félix Café', 'cafe', 'Providencia', 'Coyancura 223, local 2', -33.4198, -70.6088, 'Pequeño café de especialidad cerca del metro Pedro de Valdivia que abre temprano.', 'bajo', 'medio', 'moderado', 'pequeño, íntimo, barra', '$$', true, 'Lun-Vie 07:30-19:00, Sáb 09:00-14:00', '{"mañana":"alto","mediodia":"medio","tarde":"bajo","noche":"bajo"}'::jsonb, 'web: La Guía de Santiago + estimado por reseñas'),
('we-are-four-coffee-providencia', 'We Are Four Coffee Roasters', 'cafe', 'Providencia', 'Pedro de Valdivia 51', -33.4248, -70.6113, 'Tostaduría y café de especialidad con buena mesa para usar el notebook.', 'medio', 'alto', 'moderado', 'industrial, luminoso, barra de tostado', '$$', true, 'Lun-Vie 08:00-20:00, Sáb-Dom 09:00-19:00', '{"mañana":"medio","mediodia":"alto","tarde":"medio","noche":"bajo"}'::jsonb, 'web: prensa cafetera + estimado por reseñas'),
('cafe-triciclo-nunoa', 'Café Triciclo', 'cafe', 'Ñuñoa', 'Girardi 1569', -33.4548, -70.5985, 'Café de especialidad de barrio en Ñuñoa, con ambiente tranquilo.', 'medio', 'alto', 'moderado', 'barrio, terraza, tranquilo', '$$', true, 'Lun-Sáb 08:30-20:00', '{"mañana":"medio","mediodia":"medio","tarde":"medio","noche":"bajo"}'::jsonb, 'web: FM Dos (ruta del café Ñuñoa) + estimado'),
('casa-turquesa-nunoa', 'Casa Turquesa', 'cafe', 'Ñuñoa', 'Ortúzar 250', -33.4565, -70.5840, 'Cafetería con enchufes en cada mesa y patio, pensada para estudiar y concentrarse.', 'alto', 'alto', 'moderado', 'patio, estufas, mesas de estudio', '$$', true, 'Lun-Sáb 09:00-21:00', '{"mañana":"bajo","mediodia":"medio","tarde":"alto","noche":"medio"}'::jsonb, 'web: reseñas (cafeterías para estudiar) + estimado'),
('cafe-marelli-vitacura', 'Café Marelli', 'cafe', 'Vitacura', 'Av. Vitacura 3535', -33.4015, -70.5965, 'Café de especialidad premiado por su diseño, bueno para una pausa productiva.', 'bajo', 'medio', 'moderado', 'diseño, luminoso, minimalista', '$$$', true, 'Lun-Vie 08:00-19:00, Sáb 09:00-15:00', '{"mañana":"medio","mediodia":"alto","tarde":"medio","noche":"bajo"}'::jsonb, 'web: SCA Coffee Design Awards 2025 + estimado'),
('cafe-lo-matta-vitacura', 'Café Lo Matta', 'cafe', 'Vitacura', 'Av. Vitacura 9281', -33.3808, -70.5520, 'Cafetería de especialidad reconocida en Vitacura con terraza amplia.', 'medio', 'medio', 'animado', 'terraza, luminoso, familiar', '$$$', true, 'Lun-Dom 08:30-20:30', '{"mañana":"medio","mediodia":"alto","tarde":"alto","noche":"medio"}'::jsonb, 'web: Pullman blog (cafeterías Vitacura) + estimado'),
('between-cafe-las-condes', 'Between', 'cafe', 'Las Condes', 'Av. Vitacura 2727', -33.4150, -70.6035, 'Café relajado pensado para socializar, desconectar o trabajar con notebook.', 'medio', 'alto', 'moderado', 'relajado, luminoso, sillones', '$$', true, 'Lun-Vie 08:00-20:00, Sáb 09:00-18:00', '{"mañana":"medio","mediodia":"alto","tarde":"medio","noche":"bajo"}'::jsonb, 'web: cafeteriabetween.cl + estimado'),
('under-coffee-providencia', 'Under Coffee', 'cafe', 'Providencia', 'Galería Drugstore, Av. Providencia 2124', -33.4220, -70.6082, 'Café en la Galería Drugstore con ambiente cowork, wifi y enchufes, cerca del metro Los Leones.', 'alto', 'alto', 'moderado', 'cowork, enchufes, céntrico', '$$', true, 'Lun-Sáb 08:30-20:00', '{"mañana":"medio","mediodia":"alto","tarde":"alto","noche":"medio"}'::jsonb, 'web: reseñas (Galería Drugstore) + estimado'),
('starbucks-parque-arauco-las-condes', 'Starbucks Parque Arauco', 'cafe', 'Las Condes', 'Av. Presidente Kennedy 5413, Parque Arauco', -33.4010, -70.5780, 'Sucursal de cadena con wifi y enchufes, opción confiable para trabajar unas horas.', 'medio', 'alto', 'animado', 'cadena, amplio, mesas compartidas', '$$', true, 'Lun-Dom 09:00-21:00', '{"mañana":"medio","mediodia":"alto","tarde":"alto","noche":"medio"}'::jsonb, 'web: sitio oficial Starbucks + estimado'),
('juan-valdez-costanera-providencia', 'Juan Valdez Café Costanera Center', 'cafe', 'Providencia', 'Av. Andrés Bello 2425, Costanera Center', -33.4176, -70.6062, 'Café de cadena colombiana en Costanera Center, con enchufes y buen wifi.', 'medio', 'alto', 'animado', 'cadena, mall, concurrido', '$$', true, 'Lun-Dom 10:00-21:00', '{"mañana":"medio","mediodia":"alto","tarde":"alto","noche":"alto"}'::jsonb, 'web: sitio oficial Juan Valdez + estimado'),
('daniels-bakery-cafe-nunoa', 'Daniel''s Bakery & Café', 'cafe', 'Ñuñoa', 'Celerino Pereira 1530', -33.4530, -70.5980, 'Panadería y café de barrio en Ñuñoa, tranquilo para leer o trabajar.', 'medio', 'medio', 'moderado', 'panadería, acogedor, barrio', '$$', true, 'Lun-Sáb 08:00-20:00', '{"mañana":"medio","mediodia":"alto","tarde":"medio","noche":"bajo"}'::jsonb, 'web: FM Dos (ruta del café Ñuñoa) + estimado'),
('cafecito-house-providencia', 'Cafecito House', 'cafe', 'Providencia', 'Julio Prado 838', -33.4360, -70.6155, 'Café de especialidad que mezcla gastronomía y arte, con mesas amplias para trabajar.', 'medio', 'alto', 'moderado', 'artístico, luminoso, mesas amplias', '$$', true, 'Lun-Sáb 09:00-20:00', '{"mañana":"bajo","mediodia":"medio","tarde":"medio","noche":"bajo"}'::jsonb, 'web: La Guía de Santiago + estimado'),
('pato-nejo-santiago', 'Pato Nejo', 'cafe', 'Santiago', 'Santo Domingo 598', -33.4368, -70.6478, 'Café de especialidad en el centro histórico, buena parada para trabajar de día.', 'medio', 'medio', 'moderado', 'céntrico, casona, acogedor', '$$', true, 'Lun-Vie 08:30-19:00, Sáb 10:00-16:00', '{"mañana":"medio","mediodia":"alto","tarde":"medio","noche":"bajo"}'::jsonb, 'web: prensa gastronómica + estimado'),
('puelo-cafe-vitacura', 'Puelo Café', 'cafe', 'Vitacura', 'Las Catalpas 1522', -33.3870, -70.5560, 'Café de especialidad de barrio en Vitacura, ambiente calmo para trabajar.', 'medio', 'medio', 'moderado', 'barrio, calmo, terraza', '$$', true, 'Lun-Sáb 08:30-20:00', '{"mañana":"medio","mediodia":"medio","tarde":"medio","noche":"bajo"}'::jsonb, 'web: Pullman blog (cafeterías Vitacura) + estimado'),
('wework-apoquindo-las-condes', 'WeWork Apoquindo', 'coworking', 'Las Condes', 'Av. Apoquindo 5950', -33.4172, -70.5762, 'Coworking global en una torre de Las Condes, con salas, café y oficinas flexibles.', 'alto', 'alto', 'moderado', 'corporativo, salas de reunión, café incluido', '$$$', true, 'Lun-Vie 08:00-20:00', '{"mañana":"alto","mediodia":"medio","tarde":"alto","noche":"bajo"}'::jsonb, 'web: wework.com + estimado'),
('spaces-nueva-las-condes', 'Spaces Nueva Las Condes', 'coworking', 'Las Condes', 'Los Militares 4611, piso 17', -33.4060, -70.5710, 'Coworking de diseño con vista, salas de reunión y áreas comunes.', 'alto', 'alto', 'moderado', 'diseño, luminoso, salas de reunión', '$$$', true, 'Lun-Vie 08:30-19:00', '{"mañana":"alto","mediodia":"medio","tarde":"medio","noche":"bajo"}'::jsonb, 'web: spacesworks.com + estimado'),
('spaces-rooftop-kennedy-vitacura', 'Spaces Rooftop Kennedy', 'coworking', 'Vitacura', 'Av. Presidente Kennedy 5488', -33.3958, -70.5792, 'Coworking con rooftop y terraza en el eje Kennedy de Vitacura.', 'alto', 'alto', 'moderado', 'rooftop, terraza, moderno', '$$$', true, 'Lun-Vie 08:30-19:00', '{"mañana":"alto","mediodia":"medio","tarde":"medio","noche":"bajo"}'::jsonb, 'web: spacesworks.com + estimado'),
('spaces-el-golf-las-condes', 'Spaces El Golf', 'coworking', 'Las Condes', 'Av. El Golf 40, piso 12', -33.4148, -70.5980, 'Coworking en el barrio financiero El Golf, ideal para profesionales.', 'alto', 'alto', 'moderado', 'corporativo, financiero, salas', '$$$', true, 'Lun-Vie 08:30-19:00', '{"mañana":"alto","mediodia":"medio","tarde":"alto","noche":"bajo"}'::jsonb, 'web: spacesworks.com + estimado'),
('urban-station-los-leones-providencia', 'Urban Station Los Leones', 'coworking', 'Providencia', 'General Holley 134', -33.4202, -70.6098, 'Coworking por hora o día con estaciones de trabajo, cerca del metro Los Leones.', 'alto', 'alto', 'moderado', 'flexible, café, estaciones de trabajo', '$$', true, 'Lun-Vie 08:30-20:00, Sáb 09:00-14:00', '{"mañana":"medio","mediodia":"medio","tarde":"alto","noche":"bajo"}'::jsonb, 'web: enjoyurbanstation.com + estimado'),
('pronto-cowork-egana-la-reina', 'Pronto Cowork Mallplaza Egaña', 'coworking', 'La Reina', 'Mallplaza Egaña, Av. Larraín 5862', -33.4540, -70.5760, 'Cowork premium dentro de Mallplaza Egaña, con salas y oficinas privadas.', 'alto', 'alto', 'moderado', 'mall, moderno, salas', '$$$', true, 'Lun-Vie 08:30-20:00, Sáb 09:00-14:00', '{"mañana":"alto","mediodia":"medio","tarde":"medio","noche":"bajo"}'::jsonb, 'web: prontocowork.cl + estimado'),
('regus-moneda-santiago', 'Regus Moneda', 'coworking', 'Santiago', 'Moneda 970, piso 15', -33.4424, -70.6520, 'Oficinas con servicios y coworking en pleno centro cívico de Santiago.', 'alto', 'alto', 'moderado', 'corporativo, céntrico, salas', '$$$', true, 'Lun-Vie 08:30-18:30', '{"mañana":"alto","mediodia":"medio","tarde":"medio","noche":"bajo"}'::jsonb, 'web: regus.com + estimado'),
('biblioteca-nacional-santiago', 'Biblioteca Nacional de Chile', 'biblioteca', 'Santiago', 'Av. Libertador Bernardo O''Higgins 651', -33.4422, -70.6432, 'La principal biblioteca patrimonial del país, con salones de lectura silenciosos.', 'medio', 'alto', 'silencioso', 'patrimonial, salones, silencioso', 'gratis', true, 'Lun-Jue 09:15-18:00, Vie 09:15-17:00, Sáb 09:15-14:00', '{"mañana":"medio","mediodia":"alto","tarde":"medio","noche":"bajo"}'::jsonb, 'web: bibliotecanacional.gob.cl'),
('biblioteca-de-santiago', 'Biblioteca de Santiago', 'biblioteca', 'Santiago', 'Matucana 151', -33.4432, -70.6838, 'La biblioteca pública más grande y moderna de Chile, junto al Parque Quinta Normal.', 'alto', 'alto', 'moderado', 'amplio, luminoso, salas de estudio', 'gratis', true, 'Mar-Vie 11:00-20:00, Sáb-Dom 11:00-18:00', '{"mañana":"bajo","mediodia":"medio","tarde":"alto","noche":"bajo"}'::jsonb, 'web: bibliotecasantiago.gob.cl'),
('bibliogam-gam-santiago', 'BiblioGAM', 'biblioteca', 'Santiago', 'Av. Libertador Bernardo O''Higgins 227, Centro GAM, edificio A, nivel 3', -33.4378, -70.6405, 'Biblioteca abierta del Centro Gabriela Mistral, con gran sala de lectura y wifi.', 'alto', 'alto', 'moderado', 'moderno, luminoso, sala de lectura', 'gratis', true, 'Lun-Vie 10:00-19:30, Sáb-Dom 11:00-18:30', '{"mañana":"medio","mediodia":"alto","tarde":"alto","noche":"medio"}'::jsonb, 'web: gam.cl/bibliogam'),
('biblioteca-campus-oriente-uc-providencia', 'Biblioteca Campus Oriente UC', 'biblioteca', 'Providencia', 'Av. Jaime Guzmán Errázuriz 3300', -33.4418, -70.5980, 'Biblioteca universitaria de arte y música en el Campus Oriente UC.', 'medio', 'alto', 'silencioso', 'universitario, patios, silencioso', 'gratis', true, 'Lun-Vie 08:30-20:00', '{"mañana":"medio","mediodia":"alto","tarde":"medio","noche":"bajo"}'::jsonb, 'web: bibliotecas.uc.cl'),
('biblioteca-publica-vitacura', 'Biblioteca Pública de Vitacura', 'biblioteca', 'Vitacura', 'Av. Monseñor Escrivá de Balaguer 6420', -33.3845, -70.5630, 'Biblioteca municipal de Vitacura con salas tranquilas para el estudio.', 'medio', 'medio', 'silencioso', 'tranquilo, parque, silencioso', 'gratis', true, 'Lun-Vie 10:00-19:00, Sáb 10:30-13:30', '{"mañana":"bajo","mediodia":"medio","tarde":"medio","noche":"bajo"}'::jsonb, 'web: vitacuracultura.cl'),
('biblioteca-publica-la-reina', 'Biblioteca Pública de La Reina', 'biblioteca', 'La Reina', 'Av. Alcalde Fernando Castillo Velasco 9750', -33.4480, -70.5430, 'Biblioteca municipal de La Reina, gratuita y silenciosa para estudiar.', 'medio', 'medio', 'silencioso', 'comunitario, tranquilo, silencioso', 'gratis', true, 'Lun-Vie 09:00-18:30, Sáb 10:00-14:00', '{"mañana":"bajo","mediodia":"medio","tarde":"medio","noche":"bajo"}'::jsonb, 'web: culturalareina.cl'),
('biblioteca-central-usach-estacion-central', 'Biblioteca Central USACH', 'biblioteca', 'Estación Central', 'Av. Libertador Bernardo O''Higgins 3363', -33.4520, -70.6830, 'Biblioteca central de la Universidad de Santiago, amplia y con muchos puestos de estudio.', 'alto', 'alto', 'silencioso', 'universitario, amplio, silencioso', 'gratis', true, 'Lun-Vie 08:30-21:00, Sáb 09:00-14:00', '{"mañana":"medio","mediodia":"alto","tarde":"alto","noche":"medio"}'::jsonb, 'web: usach.cl + estimado'),
('biblioteca-san-joaquin-uc-macul', 'Biblioteca San Joaquín UC', 'biblioteca', 'Macul', 'Av. Vicuña Mackenna 4860, Campus San Joaquín UC', -33.4985, -70.6135, 'Biblioteca del Campus San Joaquín UC, gran espacio de estudio universitario.', 'alto', 'alto', 'silencioso', 'universitario, salas grupales, silencioso', 'gratis', true, 'Lun-Vie 08:30-22:00, Sáb 09:00-17:00', '{"mañana":"medio","mediodia":"alto","tarde":"alto","noche":"medio"}'::jsonb, 'web: bibliotecas.uc.cl + estimado'),
('biblioteca-fcfm-uchile-santiago', 'Biblioteca Central FCFM Universidad de Chile', 'biblioteca', 'Santiago', 'Av. Blanco Encalada 2002', -33.4575, -70.6630, 'Biblioteca de Ingeniería de la Universidad de Chile, con salas de estudio.', 'alto', 'alto', 'silencioso', 'universitario, técnico, silencioso', 'gratis', true, 'Lun-Vie 08:30-21:00', '{"mañana":"medio","mediodia":"alto","tarde":"alto","noche":"medio"}'::jsonb, 'web: uchile.cl + estimado')
on conflict (slug) do nothing;
